---
apiVersion: v2
name: linkwarden
description: A Helm chart for [Linkwarden](https://linkwarden.app/)
type: application
version: 0.1.50
appVersion: "v2.16.1"

dependencies:
  - name: meilisearch
    version: 0.38.0
    repository: https://meilisearch.github.io/meilisearch-kubernetes
