{{- if .Values.httpRoute.enabled }}
{{- if .Values.httpRoute.parentRefsHttp }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "linkwarden.name" . }}-{{ if .Values.httpRoute.redirectHttpToHttps }}https-redirect{{ else }}http{{ end }}
spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefsHttp | nindent 4 }}
  hostnames:
    {{- toYaml .Values.httpRoute.hostnames | nindent 4 }}
  rules:
    {{- if .Values.httpRoute.redirectHttpToHttps }}
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
    {{- else }}
    - backendRefs:
        - name: {{ include "linkwarden.fullname" . }}-core
          port: 3000
    {{- end }}
{{- end }}
{{- if .Values.httpRoute.parentRefsHttps }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "linkwarden.name" . }}-https
spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefsHttps | nindent 4 }}
  hostnames:
    {{- toYaml .Values.httpRoute.hostnames | nindent 4 }}
  rules:
    - backendRefs:
        - name: {{ include "linkwarden.fullname" . }}-core
          port: 3000
{{- end }}
{{- end }}
