---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "linkwarden.fullname" . }}-core
  labels:
    {{- include "linkwarden.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: core
    {{- include "linkwarden.selectorLabels" . | nindent 4 }}
